name: sync to docs

on:
  push:
    branches:
      - main # default branch
    paths:
      - '.github/workflows/**'
      - 'src/**'

jobs:
  copy:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2
      - run: node -v
      - run: npm i fs-extra --force
      - run: npm run copydocs
      - name : Sync 
        uses : JamesIves/github-pages-deploy-action@4.1.7
        with :
          branch : main # action 应该部署到的分支。
          folder : site_docs # 操作应该部署的文件夹。
          clean: false
          repository-name: hellof2e/quark-design-docs
          token: ${{ secrets.GIT_ACTION }}
          target-folder: src/docs_vue

     

          